"""Fixing posts table to include title and allow for larger body

Revision ID: 089babc6268d
Revises: c24a96b36ed2
Create Date: 2018-06-10 20:18:46.054641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "089babc6268d"
down_revision = "c24a96b36ed2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("post", sa.Column("title", sa.String(length=256), nullable=True))
    op.drop_column("post", "body")
    op.add_column("post", sa.Column("body", sa.Text, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("post", "title")
    # ### end Alembic commands ###
